shared:
    image: node:12

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=index.js -Dsonar.javascript.lcov.reportPaths=${SD_ARTIFACTS_DIR}/coverage/lcov.info"
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test
            - cp-coverage-to-artifacts: cp -r artifacts/coverage $SD_ARTIFACTS_DIR
            - cat: cat ${SD_ARTIFACTS_DIR}/artifacts/coverage/lcov.info

    publish:
        requires: main
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
